### ISSUE TITLE
Support non-x86_64 (power 9)

### ISSUE THREAD

**Issue by lu-zero** [memtt/malt#37]
Would be possible to support other architectures?
Could be possible having a porting how-to in the wiki?

**Comment by svalat** [comment]
Hi, if you speak about the RPM itself I might not have time now to make it, what it your targeted ARCH ? ARM ?

But the code itself is in principle arch independant so you should be able to build and run. The only restriction is Linux not Unix. Can be done but might need some work.

There might be some minor issues with .so/elf symbol extraction, that should be the only arch dependant part. If you encounter issues, please report I will fix in the coming days.

**Comment by lu-zero** [comment]
I tried on power9, here what I found:

- It looks for a `x86_64`-specific libunwind
``` cmake
find_library(LIBUNWIND_LIBRARY NAMES unwind-x86_64
        HINTS ${LIBUNWIND_PREFIX}/lib)
```

- `void StackSizeTracker::enter(void)` has some inline assembly.

``` cpp
void StackSizeTracker::enter(void)
{
        //get stack size
        unsigned long crbp;
        unsigned long crsp;

        //read counters
        asm("movq %%rbp,%0" : "=r"(crbp));
        asm("movq %%rsp,%0" : "=r"(crsp));
```

**Comment by svalat** [comment]
Hi, good to know.

I will make a fix as soon as possible, this should not be so much work to find the equivalent.

In the mean time, if you want to use MALT both functions are optional and not on the default way to run.

You can just comment the `asm` calls (this is used only if you use the enter-exit mode via `-finstrument-function`. But by default I'm using `backtrace()`.

For libunwind if should be optional and skiped if not found, the code will fallback to the glibc `backtrace()` function which I hope work well on power9. 

Would be happy to have feedback if you make a test.

Thanks,
Sébastien.

**Comment by svalat** [comment]
Any idea if I should search `unwind-power` of `unwind-power9` on your system, I do not have such an arch under my hand now to check ?

**Comment by svalat** [comment]
Ah or this might be unwind-ppc64 if I walk in libunwind sources ?

**Comment by lu-zero** [comment]
I see a `/usr/lib64/libunwind-ppc64.so` but why not looking for `libunwind.so`?

**Comment by lu-zero** [comment]
I tested quickly and it seems to produce a json at least.

**Comment by svalat** [comment]
Hum, you are right, didn't saw it. I made so long ago probably in a rush and forgot why I didn't took the generic one. Will fix searching the generic libunwind, thanks very much.

**Comment by svalat** [comment]
The last possible issue is onto symbol extraction for .so and -fPIE executable which can be different on power. Should not in theory. If you can check at least on a simple code doing malloc if you get the good line in source code.

**Comment by lu-zero** [comment]
Is there a cli viewer I can use to quickly test? Otherwise I'll have to setup nodejs on that machine I guess.

**Comment by svalat** [comment]
Without nodeJS no. I'm still thinking making a light ncurses based one but do not have time to do one.

If you have the sources, can you please run `./src/lib/tests/simple-case-finstr-linked` in build and send me the json file, I can give a look.

I have a unit test now for this but in a pending PR and still not finish, that's a pitty :(.

**Comment by lu-zero** [comment]
I put it [here](https://gist.github.com/lu-zero/58bf60a8ea20df6750efb4f99acdab0d)
