### ISSUE TITLE
malt is serving json and source files as xml

### ISSUE THREAD

**Issue by lu-zero** [memtt/malt#38]
Upon loading a trace I'm seeing in the browser console:

```
XML Parsing Error: syntax error
Location: http://kaby:8080/flat.json
Line Number 1, Column 1: flat.json:1:1
XML Parsing Error: syntax error
Location: http://kaby:8080/stacks.json?func=
Line Number 1, Column 1: stacks.json:1:1
XML Parsing Error: syntax error
Location: http://kaby:8080/stacks.json?func=rav1e%3A%3Aencoder%3A%3Aencode_tx_block
Line Number 1, Column 1:
stacks.json:1:1
```

And in the network tab indeed I see the type marked as xml.

Tested with firefox 67.0b15 and chrome and the behavior seems the same.

**Comment by svalat** [comment]
Hi, good to know, I never noticed, I will give a look as soon as possible, hope next week except if you need a quick fix as it should not take so long ?

Thanks for reporting.

**Comment by lu-zero** [comment]
Thank you a lot, I tried to look at the code but I never touched expressjs so I'm not sure exactly where to look at. Hopefully it can wait till next week :)
