### ISSUE TITLE
parsing JSON output

### ISSUE THREAD

**Issue by aulwes** [memtt/malt#63]
Hi, are there python modules/scripts that would help with parsing the json output in order to customize metric results?  For example, I would like to emulate what we see in webview and in my own python script be able to parse the json output and compute the inclusive/exclusive memory allocations for each function.

**Comment by svalat** [comment]
Hi,
no, there is no python scripts available.

Althrough the backend is implemented in NodeJS (javascript) so you might find a bit what you want if you look in https://github.com/memtt/malt/blob/master/src/webview/server-files/MaltProject.js. It parses the json profile file and reshape it to make it more usable in a less compressed format. It mostly unpack the source locations and function names and build summary profiles.

You can find the way to use it by looking the server implementation: https://github.com/memtt/malt/blob/master/src/webview/malt-webserver.js.

For what you asked, if you want the list of functions with their inclusive/exclusive costs : if I remeber well this should be the getFunctionFlatProfile() function.

The other way is to launch the web server and make http requests on it to get the pre-processed json file. Again for what you request this should be what is provided by '/flat.json'.

**Comment by aulwes** [comment]
Ok, thank you for the help!

**Comment by aulwes** [comment]
In the Callstack View, the arrow that connects the parent function to the child function is annotated with the memory allocated in the child from the parent.  I couldn't find out in the files you mentioned how to get the memory allocated in the child only for that parent.  Can you point to the code that calculates this amount?

**Comment by svalat** [comment]
I don't have the time to fully re-read this code now, but you can start looking at: https://github.com/memtt/malt/blob/master/src/webview/server-files/CallTreeAdapter.js#L80, this might lead you to what you want.
